// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// initializeAdapters
bool initializeAdapters(std::string nmfgpuRoot);
RcppExport SEXP nmfgpu4R_initializeAdapters(SEXP nmfgpuRootSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type nmfgpuRoot(nmfgpuRootSEXP);
    __result = Rcpp::wrap(initializeAdapters(nmfgpuRoot));
    return __result;
END_RCPP
}
// shutdownAdapters
void shutdownAdapters();
RcppExport SEXP nmfgpu4R_shutdownAdapters() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    shutdownAdapters();
    return R_NilValue;
END_RCPP
}
// cppChooseGpu
bool cppChooseGpu(int index);
RcppExport SEXP nmfgpu4R_cppChooseGpu(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    __result = Rcpp::wrap(cppChooseGpu(index));
    return __result;
END_RCPP
}
// cppNumberOfGpu
unsigned cppNumberOfGpu();
RcppExport SEXP nmfgpu4R_cppNumberOfGpu() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(cppNumberOfGpu());
    return __result;
END_RCPP
}
// cppInfoForGpuIndex
Rcpp::List cppInfoForGpuIndex(unsigned index);
RcppExport SEXP nmfgpu4R_cppInfoForGpuIndex(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned >::type index(indexSEXP);
    __result = Rcpp::wrap(cppInfoForGpuIndex(index));
    return __result;
END_RCPP
}
// adapterComputeSinglePrecision
SEXP adapterComputeSinglePrecision(const std::string& algorithm, const std::string& initMethod, Rcpp::NumericMatrix V, int features, int seed, double threshold, unsigned maxiter, unsigned runs, Rcpp::List parameters, bool verbose, bool ssnmf);
RcppExport SEXP nmfgpu4R_adapterComputeSinglePrecision(SEXP algorithmSEXP, SEXP initMethodSEXP, SEXP VSEXP, SEXP featuresSEXP, SEXP seedSEXP, SEXP thresholdSEXP, SEXP maxiterSEXP, SEXP runsSEXP, SEXP parametersSEXP, SEXP verboseSEXP, SEXP ssnmfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type initMethod(initMethodSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< unsigned >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< unsigned >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type ssnmf(ssnmfSEXP);
    __result = Rcpp::wrap(adapterComputeSinglePrecision(algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf));
    return __result;
END_RCPP
}
// adapterComputeDoublePrecision
SEXP adapterComputeDoublePrecision(const std::string& algorithm, const std::string& initMethod, Rcpp::NumericMatrix V, int features, int seed, double threshold, unsigned maxiter, unsigned runs, Rcpp::List parameters, bool verbose, bool ssnmf);
RcppExport SEXP nmfgpu4R_adapterComputeDoublePrecision(SEXP algorithmSEXP, SEXP initMethodSEXP, SEXP VSEXP, SEXP featuresSEXP, SEXP seedSEXP, SEXP thresholdSEXP, SEXP maxiterSEXP, SEXP runsSEXP, SEXP parametersSEXP, SEXP verboseSEXP, SEXP ssnmfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type initMethod(initMethodSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< unsigned >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< unsigned >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type ssnmf(ssnmfSEXP);
    __result = Rcpp::wrap(adapterComputeDoublePrecision(algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf));
    return __result;
END_RCPP
}
// adapterComputeSinglePrecisionSparse
SEXP adapterComputeSinglePrecisionSparse(const std::string& algorithm, const std::string& initMethod, Rcpp::RObject sparseV, int features, int seed, double threshold, unsigned maxiter, unsigned runs, Rcpp::List parameters, bool verbose, bool ssnmf);
RcppExport SEXP nmfgpu4R_adapterComputeSinglePrecisionSparse(SEXP algorithmSEXP, SEXP initMethodSEXP, SEXP sparseVSEXP, SEXP featuresSEXP, SEXP seedSEXP, SEXP thresholdSEXP, SEXP maxiterSEXP, SEXP runsSEXP, SEXP parametersSEXP, SEXP verboseSEXP, SEXP ssnmfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type initMethod(initMethodSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type sparseV(sparseVSEXP);
    Rcpp::traits::input_parameter< int >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< unsigned >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< unsigned >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type ssnmf(ssnmfSEXP);
    __result = Rcpp::wrap(adapterComputeSinglePrecisionSparse(algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf));
    return __result;
END_RCPP
}
// adapterComputeDoublePrecisionSparse
SEXP adapterComputeDoublePrecisionSparse(const std::string& algorithm, const std::string& initMethod, Rcpp::RObject sparseV, int features, int seed, double threshold, unsigned maxiter, unsigned runs, Rcpp::List parameters, bool verbose, bool ssnmf);
RcppExport SEXP nmfgpu4R_adapterComputeDoublePrecisionSparse(SEXP algorithmSEXP, SEXP initMethodSEXP, SEXP sparseVSEXP, SEXP featuresSEXP, SEXP seedSEXP, SEXP thresholdSEXP, SEXP maxiterSEXP, SEXP runsSEXP, SEXP parametersSEXP, SEXP verboseSEXP, SEXP ssnmfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type initMethod(initMethodSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type sparseV(sparseVSEXP);
    Rcpp::traits::input_parameter< int >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< unsigned >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< unsigned >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type ssnmf(ssnmfSEXP);
    __result = Rcpp::wrap(adapterComputeDoublePrecisionSparse(algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf));
    return __result;
END_RCPP
}
// adapterSetCallback
void adapterSetCallback(Rcpp::Function func);
RcppExport SEXP nmfgpu4R_adapterSetCallback(SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::Function >::type func(funcSEXP);
    adapterSetCallback(func);
    return R_NilValue;
END_RCPP
}
// nmfgpuVersionString
std::string nmfgpuVersionString();
RcppExport SEXP nmfgpu4R_nmfgpuVersionString() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(nmfgpuVersionString());
    return __result;
END_RCPP
}
