# nmfgpu4R - R binding for the nmfgpu library
# 
# Copyright (C) 2015-2016  Sven Koitka (sven.koitka@fh-dortmund.de)
# 
# This file is part of nmfgpu4R.
# 
# nmfgpu4R is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# nmfgpu4R is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with nmfgpu4R.  If not, see <http://www.gnu.org/licenses/>.

# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initializeAdapters <- function(nmfgpuRoot) {
    .Call('nmfgpu4R_initializeAdapters', PACKAGE = 'nmfgpu4R', nmfgpuRoot)
}

shutdownAdapters <- function() {
    invisible(.Call('nmfgpu4R_shutdownAdapters', PACKAGE = 'nmfgpu4R'))
}

cppChooseGpu <- function(index) {
    .Call('nmfgpu4R_cppChooseGpu', PACKAGE = 'nmfgpu4R', index)
}

cppNumberOfGpu <- function() {
    .Call('nmfgpu4R_cppNumberOfGpu', PACKAGE = 'nmfgpu4R')
}

cppInfoForGpuIndex <- function(index) {
    .Call('nmfgpu4R_cppInfoForGpuIndex', PACKAGE = 'nmfgpu4R', index)
}

adapterComputeSinglePrecision <- function(algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf) {
    .Call('nmfgpu4R_adapterComputeSinglePrecision', PACKAGE = 'nmfgpu4R', algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf)
}

adapterComputeDoublePrecision <- function(algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf) {
    .Call('nmfgpu4R_adapterComputeDoublePrecision', PACKAGE = 'nmfgpu4R', algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf)
}

adapterComputeSinglePrecisionSparse <- function(algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf) {
    .Call('nmfgpu4R_adapterComputeSinglePrecisionSparse', PACKAGE = 'nmfgpu4R', algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf)
}

adapterComputeDoublePrecisionSparse <- function(algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf) {
    .Call('nmfgpu4R_adapterComputeDoublePrecisionSparse', PACKAGE = 'nmfgpu4R', algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf)
}

adapterSetCallback <- function(func) {
    invisible(.Call('nmfgpu4R_adapterSetCallback', PACKAGE = 'nmfgpu4R', func))
}

nmfgpuVersionString <- function() {
    .Call('nmfgpu4R_nmfgpuVersionString', PACKAGE = 'nmfgpu4R')
}

