# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adapterComputeKMeansSingle <- function(pData, k, seed, maxiter, threshold) {
    .Call('nmfgpu4R_adapterComputeKMeansSingle', PACKAGE = 'nmfgpu4R', pData, k, seed, maxiter, threshold)
}

adapterComputeKMeansDouble <- function(pData, k, seed, maxiter, threshold) {
    .Call('nmfgpu4R_adapterComputeKMeansDouble', PACKAGE = 'nmfgpu4R', pData, k, seed, maxiter, threshold)
}

initializeAdapters <- function(nmfgpuRoot) {
    .Call('nmfgpu4R_initializeAdapters', PACKAGE = 'nmfgpu4R', nmfgpuRoot)
}

shutdownAdapters <- function() {
    invisible(.Call('nmfgpu4R_shutdownAdapters', PACKAGE = 'nmfgpu4R'))
}

chooseGpuImpl <- function(index) {
    .Call('nmfgpu4R_chooseGpuImpl', PACKAGE = 'nmfgpu4R', index)
}

getNumberOfGpu <- function() {
    .Call('nmfgpu4R_getNumberOfGpu', PACKAGE = 'nmfgpu4R')
}

getInfoForGpuIndex <- function(index) {
    .Call('nmfgpu4R_getInfoForGpuIndex', PACKAGE = 'nmfgpu4R', index)
}

adapterComputeSinglePrecision <- function(algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf) {
    .Call('nmfgpu4R_adapterComputeSinglePrecision', PACKAGE = 'nmfgpu4R', algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf)
}

adapterComputeDoublePrecision <- function(algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf) {
    .Call('nmfgpu4R_adapterComputeDoublePrecision', PACKAGE = 'nmfgpu4R', algorithm, initMethod, V, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf)
}

adapterComputeSinglePrecisionSparse <- function(algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf) {
    .Call('nmfgpu4R_adapterComputeSinglePrecisionSparse', PACKAGE = 'nmfgpu4R', algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf)
}

adapterComputeDoublePrecisionSparse <- function(algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf) {
    .Call('nmfgpu4R_adapterComputeDoublePrecisionSparse', PACKAGE = 'nmfgpu4R', algorithm, initMethod, sparseV, features, seed, threshold, maxiter, runs, parameters, verbose, ssnmf)
}

adapterSetCallback <- function(func) {
    invisible(.Call('nmfgpu4R_adapterSetCallback', PACKAGE = 'nmfgpu4R', func))
}

